filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log               # watch all logs
    fields_under_root: true

    multiline:
      pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}"
      negate: true
      match: after

    include_lines: ["DEBUG", "INFO", "WARN", "ERROR", "TRACE"]

    # Filter for default & dev service logs only
    include_files:
      - ".*-service.log"           # default service logs
    exclude_files:
      - ".*-service-dev.log"       # dev environment logs
      - ".*-service-stage.log"     # skip stage logs
      - ".*-service-prod.log"      # skip prod logs

    # Dynamically extract service name and environment from filename
    processors:
      - dissect:
          tokenizer: "/logs/%{service.name}.log"
          field: "log.file.path"
          target_prefix: ""
      - add_fields:
          fields:
            environment: "local"
            log_level: "detailed"

output.logstash:
  hosts: ["logstash:5044"]

logging.level: debug
