filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log               # watch all logs
    fields_under_root: true

    multiline:
      pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}"
      negate: true
      match: after

    include_lines: ["DEBUG", "INFO", "WARN", "ERROR", "TRACE"]

    # Filter for default & dev service logs only
    include_files:
      - ".*-service.log"           # default service logs
    exclude_files:
      - ".*-service-dev.log"       # dev environment logs
      - ".*-service-stage.log"     # skip stage logs
      - ".*-service-prod.log"      # skip prod logs

    # Dynamically extract service name and environment from filename
    processors:
      - dissect:
          tokenizer: "/logs/%{service}-service-%{environment}.log"
          field: "log.file.path"
          target_prefix: ""
      - add_fields:
          fields:
            log_level: "detailed"

  # Docker container logs
  # - type: container
  #   enabled: true
  #   paths:
  #     - "/var/lib/docker/containers/*/*.log"
  #   processors:
  #     - add_docker_metadata:
  #         host: "unix:///var/run/docker.sock"
  #     - add_fields:
  #         fields:
  #           log_level: "detailed"

# 🔽 Instead of Logstash, output to a file
# output.file:
#   path: "/tmp/filebeat-logs" # folder where logs will be written
#   filename: "filebeat-logs" # base name of the log file
#   rotate_every_kb: "10000" # rotate file every 10MB
#   number_of_files: "5" # keep last 5 rotated files

output.logstash:
  hosts: ["logstash:5044"]

logging.level: debug
