version: "3.8"

services:
  # PostgreSQL Database Production
  postgres:
    container_name: postgres-prod
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  # PG Admin for database management
  pgadmin:
    container_name: pgadmin-prod
    ports:
      - "5052:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@prod.com
    volumes:
      - pgadmin_data_prod:/var/lib/pgadmin

volumes:
  postgres_data_prod:
  pgadmin_data_prod: