version: "3.8"

services:
  # PostgreSQL Database Dev
  postgres:
    container_name: postgres-dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  # PG Admin for database management
  pgadmin:
    container_name: pgadmin-dev
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dev.com
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin

volumes:
  postgres_data_dev:
  pgadmin_data_dev:
