version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres-staging
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - elk-network
    
  # PG Admin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-staging
    depends_on:
      - postgres
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@staging.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data_staging:/var/lib/pgadmin
    networks:
      - elk-network
  
  # kafka based services(Zookeeper-free)
  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    ports:
      - "9192:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    environment:
      # Enable KRaft mode
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9192
      # Generate a cluster ID
      - KAFKA_CLUSTER_ID=2kE8VqPSTxW0628p_87f2A
    networks:
      - elk-network
  
  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elk-network
  
  # Logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - elk-network
  
  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    networks:
      - elk-network
  
  # Filebeat
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: filebeat
    depends_on:
      - logstash
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/logs:ro          # <--- map the local logs folder
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # for dockerlogs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elk-network
    command: filebeat -e -strict.perms=false

volumes:
  postgres_data_staging:
  elasticsearch_data:
  pgadmin_data_staging:
  kafka_data:

networks:
  elk-network:
    driver: bridge